### PR TITLE
Create welcome iOS app

### PR DESCRIPTION
**Pull request by danielpassos**
See: [FH-2479](https://issues.jboss.org/browse/FH-2479)

### CODE REVIEW

**Comment by danielpassos** [comment]
@corinnekrych Could you review that?

**Comment by corinnekrych** [comment]
:eyes:

**Comment by corinnekrych** [comment]
@danielpassos +1
Great work!
Here is a PR for spelling mistakes: https://github.com/danielpassos/welcome-ios/pull/1
On side note: when fhconfig.plist is not populated and you try to do a cloud call, the app crashed. 
this is because the FH.init done in AppDelegate fails and the user was not pop-up about it. we could improve by letting the user know like we did for helloworld-ios.
I've done a separate ticket for this: FH-2623. 

We can merge this PR once spelling PR is merged.

**Comment by danielpassos** [comment]
@corinnekrych Done. Thanks to open a new Jira for FH init

**Pull request merged**
